name: keluarga-cemara
options:
  bundleIdPrefix: com.cemara
  settings:
    iOS:
      TARGETED_DEVICE_FAMILY: "1"  # 1 for iPhone, 2 for iPad
targets:
  keluarga-cemara:
    type: application
    platform: iOS
    deploymentTarget: "16.6"
    sources:
      - keluarga-cemara
    info:
      path: keluarga-cemara/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: "APPL"
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1.0.0"
        UILaunchStoryboardName: "LaunchScreen"
        UISupportedInterfaceOrientations:
          - "UIInterfaceOrientationPortrait"
          - "UIInterfaceOrientationLandscapeLeft"
          - "UIInterfaceOrientationLandscapeRight"
        UISupportedInterfaceOrientations~ipad:
          - "UIInterfaceOrientationPortrait"
          - "UIInterfaceOrientationPortraitUpsideDown"
          - "UIInterfaceOrientationLandscapeLeft"
          - "UIInterfaceOrientationLandscapeRight"
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
        NSCameraUsageDescription: "Need for room plan"
