name: keluarga-cemara
options:
  bundleIdPrefix: com.cemara
  settings:
    iOS:
      TARGETED_DEVICE_FAMILY: "1"  # 1 for iPhone, 2 for iPad
packages:
  SunKit:
    url: https://github.com/Sunlitt/SunKit
    from: 2.7.0
  Lottie:
    url: https://github.com/airbnb/lottie-ios
    from: 4.3.3
targets:
  keluarga-cemara:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - keluarga-cemara
    dependencies:
      - package: SunKit
      - package: Lottie
